language: python

python:
- '2.7'

install: pip install -r requirements.txt --use-mirrors

script: nosetests

deploy:
  provider: pypi
  user: azavea
  password:
      secure: S4FQSkKrvNl+D+w/2hMBKf2DWmk0naC44/YMmDODsmJ0Te9iP7zs2pS9RQ9rWA9mcRMSEK3yTLcPvRTA0MBYIKcDmhCjKRNMSy/vEVtbP6+/WH+gFZvO/yq1wz/illmY6PQeN90enPOiJFff2Q5BDRRNk9zZ5yfML8bLvkJZn6A=
  on:
    tags: true
    repo: mmcfarland/tr-55
    branch: feature/travis-2.7
