language: python
python:
- '2.7'
install: pip install -r requirements.txt --use-mirrors
script: nosetests
deploy:
  provider: pypi
  user: azavea
  password:
    secure: b6LhrJWeE4jiT6SawnEMPtc8bxwP8a0W09XUxLuHGkDX3Iiyw9n8glDBokizNUdFdVza1L+1M6VrBItlFpWm33qaNWdR2t6Ji4+hsiw2hiV7e+f8iM0AOM1b1fFojfAzOc4SYDuhR7D4eb2h3Y8ZC5Z/VIFYsfWlTPQWr2TRDkM=
  on:
    tags: true
    repo: mmcfarland/tr-55
    branch: feature/travis-2.7
